import os
from abc import ABC, abstractmethod
from typing import Optional, List

from lanarky.responses import StreamingResponse
from langchain.chat_models.base import BaseChatModel

from reworkd_platform.db.crud.oauth import OAuthCrud
from reworkd_platform.schemas.user import UserBase


class Tool(ABC):
    description: str = ""
    public_description: str = ""
    arg_description: str = "The argument to the function."
    image_url: str = "/tools/openai-white.png"

    model: BaseChatModel
    language: str

    def __init__(self, model: BaseChatModel, language: str):
        self.model = model
        self.language = language

    @staticmethod
    def available() -> bool:
        return True

    @staticmethod
    async def dynamic_available(user: UserBase, oauth_crud: OAuthCrud) -> bool:
        return True

    @abstractmethod
    async def call(
        self,
        goal: str,
        task: str,
        input_str: str,
        user: UserBase,
        oauth_crud: OAuthCrud,
    ) -> StreamingResponse:
        """
        Abstract method that needs to be implemented by subclasses.
        It is expected to perform a specific task based on the provided goal, task, and input string.
        The user and oauth_crud parameters are used for user authentication and authorization.

        Parameters:
        goal (str): The goal of the task.
        task (str): The specific task to be performed.
        input_str (str): The input string for the task.
        user (UserBase): The user performing the task.
        oauth_crud (OAuthCrud): The OAuth CRUD operations.

        Returns:
        StreamingResponse: The response of the task.
        """
        pass

    def read_from_shared_folder(self, file_name: str) -> str:
        """
        Reads a file from a shared folder and returns its content as a string.

        Parameters:
        file_name (str): The name of the file to be read.

        Returns:
        str: The content of the file.
        """
        with open(f'SharedFolder/{file_name}', 'r') as file:
            return file.read()

    def write_to_shared_folder(self, file_name: str, content: str) -> None:
        """
        Writes content to a file in a shared folder.
        If the file already exists, a new version of the file is created.

        Parameters:
        file_name (str): The name of the file to be written.
        content (str): The content to be written to the file.
        """
        if os.path.exists(f'SharedFolder/{file_name}'):
            version = 1
            while os.path.exists(f'SharedFolder/{file_name}_{version}'):
                version += 1
            file_name = f'{file_name}_{version}'
        with open(f'SharedFolder/{file_name}', 'w') as file:
            file.write(content)

    def is_code_relevant(self, code: str, task: str) -> bool:
        """
        Checks if all keywords from a task are present in a given code string.

        Parameters:
        code (str): The code string to be checked.
        task (str): The task whose keywords are to be checked in the code.

        Returns:
        bool: True if all keywords are present in the code, False otherwise.
        """
        keywords = task.split(' ')
        for keyword in keywords:
            if keyword not in code:
                return False
        return True

    def generate_tags(self, code: str) -> List[str]:
        """
        Generates tags for a given code string.
        The tags are generated by extracting the function name, parameters, and generating a one-sentence summary.

        Parameters:
        code (str): The code string for which tags are to be generated.

        Returns:
        List[str]: The generated tags.
        """
        function_name = # extract function name from code
        parameters = # extract parameters from code
        summary = # generate a one-sentence summary of the code
        return [function_name, parameters, summary]
        """
        Writes content to a file in a shared folder.
        If the file already exists, a new version of the file is created.

        Parameters:
        file_name (str): The name of the file to be written.
        content (str): The content to be written to the file.
        """
        if os.path.exists(f'SharedFolder/{file_name}'):
            version = 1
            while os.path.exists(f'SharedFolder/{file_name}_{version}'):
                version += 1
            file_name = f'{file_name}_{version}'
        with open(f'SharedFolder/{file_name}', 'w') as file:
            file.write(content)

    def is_code_relevant(self, code: str, task: str) -> bool:
        keywords = task.split(' ')
        for keyword in keywords:
            if keyword not in code:
                return False
        return True

    def generate_tags(self, code: str) -> List[str]:
        function_name = # extract function name from code
        parameters = # extract parameters from code
        summary = # generate a one-sentence summary of the code
        return [function_name, parameters, summary]